import path from 'node:path';
import { fileURLToPath } from 'node:url';

import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactCompiler from 'eslint-plugin-react-compiler';
import tseslint from 'typescript-eslint';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** @type {import('eslint').Linter.Config} */
const config = [
  js.configs.recommended,

  {
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
      },
    },
  },

  jsxA11y.flatConfigs.recommended,
  // patch next core-web-vitals to not conflict with eslint-plugin-jsx-a11y
  ...nextCoreWebVitals.map((config) => {
    if (config.plugins?.['jsx-a11y']) {
      const { 'jsx-a11y': _, ...restPlugins } = config.plugins;
      return {
        ...config,
        plugins: restPlugins,
      };
    }
    return config;
  }),

  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        projectService: {
          allowDefaultProject: ['*.js', '*.mjs', '*.cjs'],
        },
        tsconfigRootDir: __dirname,
      },
    },

    plugins: {
      'react-compiler': reactCompiler,
    },

    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          ignoreRestSiblings: true,
        },
      ],

      'react-compiler/react-compiler': 'error',

      // accessingv these as globals is generally a bad idea
      'no-restricted-globals': [
        'error',
        'postMessage',
        'blur',
        'focus',
        'close',
        'frames',
        'self',
        'parent',
        'opener',
        'top',
        'length',
        'closed',
        'location',
        'origin',
        'name',
        'locationbar',
        'menubar',
        'personalbar',
        'scrollbars',
        'statusbar',
        'toolbar',
        'status',
        'frameElement',
        'navigator',
        'customElements',
        'external',
        'screen',
        'innerWidth',
        'innerHeight',
        'scrollX',
        'pageXOffset',
        'scrollY',
        'pageYOffset',
        'screenX',
        'screenY',
        'outerWidth',
        'outerHeight',
        'devicePixelRatio',
        'clientInformation',
        'screenLeft',
        'screenTop',
        'defaultStatus',
        'defaultstatus',
        'styleMedia',
        'onanimationend',
        'onanimationiteration',
        'onanimationstart',
        'onsearch',
        'ontransitionend',
        'onwebkitanimationend',
        'onwebkitanimationiteration',
        'onwebkitanimationstart',
        'onwebkittransitionend',
        'isSecureContext',
        'onabort',
        'onblur',
        'oncancel',
        'oncanplay',
        'oncanplaythrough',
        'onchange',
        'onclick',
        'onclose',
        'oncontextmenu',
        'oncuechange',
        'ondblclick',
        'ondrag',
        'ondragend',
        'ondragenter',
        'ondragleave',
        'ondragover',
        'ondragstart',
        'ondrop',
        'ondurationchange',
        'onemptied',
        'onended',
        'onerror',
        'onfocus',
        'oninput',
        'oninvalid',
        'onkeydown',
        'onkeypress',
        'onkeyup',
        'onload',
        'onloadeddata',
        'onloadedmetadata',
        'onloadstart',
        'onmousedown',
        'onmouseenter',
        'onmouseleave',
        'onmousemove',
        'onmouseout',
        'onmouseover',
        'onmouseup',
        'onmousewheel',
        'onpause',
        'onplay',
        'onplaying',
        'onprogress',
        'onratechange',
        'onreset',
        'onresize',
        'onscroll',
        'onseeked',
        'onseeking',
        'onselect',
        'onstalled',
        'onsubmit',
        'onsuspend',
        'ontimeupdate',
        'ontoggle',
        'onvolumechange',
        'onwaiting',
        'onwheel',
        'onauxclick',
        'ongotpointercapture',
        'onlostpointercapture',
        'onpointerdown',
        'onpointermove',
        'onpointerup',
        'onpointercancel',
        'onpointerover',
        'onpointerout',
        'onpointerenter',
        'onpointerleave',
        'onafterprint',
        'onbeforeprint',
        'onbeforeunload',
        'onhashchange',
        'onlanguagechange',
        'onmessage',
        'onmessageerror',
        'onoffline',
        'ononline',
        'onpagehide',
        'onpageshow',
        'onpopstate',
        'onrejectionhandled',
        'onstorage',
        'onunhandledrejection',
        'onunload',
        'performance',
        'stop',
        'open',
        'print',
        'captureEvents',
        'releaseEvents',
        'getComputedStyle',
        'matchMedia',
        'moveTo',
        'moveBy',
        'resizeTo',
        'resizeBy',
        'getSelection',
        'find',
        'createImageBitmap',
        'scroll',
        'scrollTo',
        'scrollBy',
        'onappinstalled',
        'onbeforeinstallprompt',
        'crypto',
        'ondevicemotion',
        'ondeviceorientation',
        'ondeviceorientationabsolute',
        'indexedDB',
        'webkitStorageInfo',
        'chrome',
        'visualViewport',
        'speechSynthesis',
        'webkitRequestFileSystem',
        'webkitResolveLocalFileSystemURL',
        'openDatabase',
      ],
    },
  },
];

export default config;
